In [1]:
import torch
import numpy as np

In [12]:
# convert numpy to tensor or vise versa
np_data = np.arange(6)
np_data = np_data.reshape(2,3)
print(np_data) 
torch_data = torch.from_numpy(np_data)
print(torch_data)
tensor2array = torch_data.numpy()
print(tensor2array)

[[0 1 2]
 [3 4 5]]

 0  1  2
 3  4  5
[torch.LongTensor of size 2x3]

[[0 1 2]
 [3 4 5]]


In [16]:
# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)
print(
    '\nabs',
    '\nnumpy: ', np.abs(data),          # [1 2 1 2]
    '\ntorch: ', torch.abs(tensor)      # [1 2 1 2]
)


abs 
numpy:  [1 2 1 2] 
torch:  
 1
 2
 1
 2
[torch.FloatTensor of size 4]



In [17]:
tensor.abs()


 1
 2
 1
 2
[torch.FloatTensor of size 4]

In [18]:
# sin
print(
    '\nsin',
    '\nnumpy: ', np.sin(data),      # [-0.84147098 -0.90929743  0.84147098  0.90929743]
    '\ntorch: ', torch.sin(tensor)  # [-0.8415 -0.9093  0.8415  0.9093]
)



sin 
numpy:  [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch:  
-0.8415
-0.9093
 0.8415
 0.9093
[torch.FloatTensor of size 4]



In [22]:
tensor.sin()


-0.8415
-0.9093
 0.8415
 0.9093
[torch.FloatTensor of size 4]

In [19]:
tensor.sigmoid()


 0.2689
 0.1192
 0.7311
 0.8808
[torch.FloatTensor of size 4]

In [20]:
tensor.exp()


 0.3679
 0.1353
 2.7183
 7.3891
[torch.FloatTensor of size 4]

In [31]:
# matrix multiplication
data = [[1,2],[3,4]]
tensor = torch.FloatTensor(data)

print(np.matmul(data,data))
print(torch.mm(tensor,tensor))

[[ 7 10]
 [15 22]]

  7  10
 15  22
[torch.FloatTensor of size 2x2]

